### ISSUE TITLE
Question about LID

### ISSUE THREAD

**Issue by PoseidomWong** [aldahdooh/detectors_review#3]
I'm sorry to disturb you. I would like to ask you how do you calculate the noise parameters in LID? If I switch to imagenet dataset, how do I compute these noise parameters?

`'cifar': {'fgsm_0.03125': 0.03125, 'fgsm_0.0625': 0.0625, 'fgsm_0.125': 0.125, 'fgsm_0.25': 0.25, 'fgsm_0.3125': 0.3125, 'fgsm_0.5': 0.5,\
            'bim_0.03125': 0.03125, 'bim_0.0625': 0.0625, 'bim_0.125': 0.125, 'bim_0.25': 0.25, 'bim_0.3125': 0.3125, 'bim_0.5': 0.5,\
            'pgd1_5': 0.03125, 'pgd1_10': 0.0625, 'pgd1_15': 0.125, 'pgd1_20': 0.125, 'pgd1_25': 0.125, 'pgd1_30': 0.25, 'pgd1_40': 0.3125,\
            'pgd2_0.25': 0.03125, 'pgd2_0.3125': 0.0625, 'pgd2_0.5': 0.125, 'pgd2_1': 0.125, 'pgd2_1.5': 0.25, 'pgd2_2': 0.3125,\
            'pgdi_0.03125': 0.03125, 'pgdi_0.0625': 0.0625, 'pgdi_0.125': 0.125, 'pgdi_0.25': 0.25, 'pgdi_0.3125': 0.3125, 'pgdi_0.5': 0.5,\
            'cwi': 0.125, 'df': 0.125,\
            'hca_0.03125': 0.03125, 'hca_0.0625': 0.0625, 'hca_0.125': 0.125, 'hca_0.25': 0.25, 'hca_0.3125': 0.3125, 'hca_0.5': 0.5,\
            'sa': 0.125, 'sta': 0.125, 'hop': 0.125
            },`

**Comment by aldahdooh** [comment]
Hi @PoseidomWong 
Regarding your question, these numbers has to be tuned according to your adversarial samples. In my code, I just highlighted that each attack has its own STDEVS. I followed the steps mentioned in KD+BU detector paper (same of LID steps). 

In the original paper of KD+BU:
For L0 attacks: observe the number of pixels that were altered in the adversarial case and flip an equal number of pixels randomly to their min or max values. 
For Other attacks: noisy samples are crafted by adding Guassian noise to each pixel with a scale set so that the mean L2-norm of the perturbation matches that of the adversarial samples.

**Comment by PoseidomWong** [comment]
So all of these attacks, except for L0 attacks, take the adversarial sample and subtract the original sample to get the L2 norm, divide by the pixel numbers, and then average those results, right? Thank you for your reply.

**Comment by aldahdooh** [comment]
@PoseidomWong 
perturbation_adv = original-adversarial
l2_diff_adv = mean(l2(perturbation_adv)) 

perturbation_noisy = original-noisy
l2_diff_noisy = mean(l2(perturbation_noisy)) 

You need to set STDEV of the Gaussian noise when l2_diff_adv == l2_diff_noisy

**Comment by PoseidomWong** [comment]
I see. Thank you very much and wish you all the best
